[package]
name = "cleanup"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
csv = "1"
once_cell = "1"
regex = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
unicode-normalization = "0.1"
walkdir = "2"
